//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FamilyProjectEntities5 : DbContext
    {
        public FamilyProjectEntities5()
            : base("name=FamilyProjectEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<RelationshipKey> RelationshipKeys { get; set; }
        public virtual DbSet<tbl_RegisteredUsers> tbl_RegisteredUsers { get; set; }
    
        [DbFunction("FamilyProjectEntities5", "FN_GetGenneration")]
        public virtual IQueryable<FN_GetGenneration_Result> FN_GetGenneration(Nullable<int> userInput, Nullable<int> userStatus, Nullable<int> increments)
        {
            var userInputParameter = userInput.HasValue ?
                new ObjectParameter("UserInput", userInput) :
                new ObjectParameter("UserInput", typeof(int));
    
            var userStatusParameter = userStatus.HasValue ?
                new ObjectParameter("UserStatus", userStatus) :
                new ObjectParameter("UserStatus", typeof(int));
    
            var incrementsParameter = increments.HasValue ?
                new ObjectParameter("Increments", increments) :
                new ObjectParameter("Increments", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_GetGenneration_Result>("[FamilyProjectEntities5].[FN_GetGenneration](@UserInput, @UserStatus, @Increments)", userInputParameter, userStatusParameter, incrementsParameter);
        }
    
        public virtual ObjectResult<SP_PullingRelatives_Result> SP_PullingRelatives()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PullingRelatives_Result>("SP_PullingRelatives");
        }

        public System.Data.Entity.DbSet<CapstoneProject.Models.RegisterViewModel> RegisterViewModels { get; set; }
    }
}
