//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public long ID { get; set; }
        public long PersonID { get; set; }
        public long SecondPersonID { get; set; }
        public short RID { get; set; }
    
        public virtual Family Family1 { get; set; }
        public virtual Family Family2 { get; set; }
        public virtual Family Family11 { get; set; }
        public virtual Family Family3 { get; set; }
        public virtual Family Family12 { get; set; }
        public virtual Family Family4 { get; set; }
    }
}
