//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Families = new HashSet<Family>();
            this.Families1 = new HashSet<Family>();
        }
    
        public long PersonID { get; set; }
        public string PersonName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<System.DateTime> MarriedDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string CurrentLocation { get; set; }
        public string Email { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Families { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Families1 { get; set; }
    }
}
