//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegisteredUsers
    {
        public long PersonID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> MarriedDate { get; set; }
        public string CurrentLocation { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
